/* HuSS Scorer — js/strings.en.js
 * Every interface text. A translation is a copy of this file with the same keys.
 * Placeholders: {name}.
 */
(function (root) {
  'use strict';
  var HUSS = root.HUSS = root.HUSS || {};

  HUSS.strings = {
    app_title: 'HuSS Scorer',
    phase_badge: 'Phase 2 prototype',
    open_image: 'Open image…',

    drop_title: 'Drop a folder of scanned HuSS drawings here',
    drop_sub: 'JPEG or PNG, colour scans at 300 dpi. The images stay on this computer. Enter your rater code and choose a mode first.',
    drop_button: 'Choose folder…',
    drop_button_files: 'Choose files…',
    busy: 'Aligning and detecting…',

    fit: 'Fit',
    zoom_in: 'Zoom in (+)',
    zoom_out: 'Zoom out (−)',
    hint_idle: 'Wheel: zoom · Space + drag or drag empty paper: pan · 1–4: select handle · Arrows: nudge (Shift ×10) · Alt: no snap · Enter: confirm',
    hint_place: 'Click on the drawing to place the {name} handle. Esc cancels.',
    hint_foot_locked: 'The foot handle is locked. Unlock it in the panel to move it.',

    sec_session: 'Session',
    project_code: 'Project code',
    rater_code: 'Rater code *',
    rater_code_placeholder: 'your initials, e.g. EY',
    rater_code_help: 'Who is scoring: your initials or a short code. Required; it is written into the CSV.',
    sheet_code: 'Sheet code',
    sheet_code_placeholder: 'e.g. 6QHJ4',
    sheet_code_hint: 'The QR code could not be read: type the 5 characters printed next to the QR square (see the picture).',
    sheet_code_ok: 'Check character OK',
    sheet_code_bad: 'Not a sheet code. Copy the 5 characters printed at the bottom right, next to the QR square (they never contain 0, 1, I, O or S).',

    sec_image: 'Image',
    no_image: 'No image loaded.',
    align_summary: 'Aligned automatically · {r} px/mm · residual {res} mm · rotation {rot}°',
    align_summary_manual_corners: 'Aligned by hand (corner squares) · {r} px/mm · residual {res} mm · rotation {rot}°',
    align_summary_manual_floorline: 'Aligned by hand (floor line ends) · {r} px/mm · rotation {rot}°',

    // Manual alignment (spec 7.5)
    sec_manual: 'Manual alignment',
    manual_why_corners_not_found: 'The corner marks of this sheet could not be found automatically. Align it by hand, then score it as usual.',
    manual_why_orientation_failed: 'The page orientation could not be found automatically. Align it by hand, then score it as usual.',
    manual_method_corners: '4 corner squares',
    manual_method_floorline: '2 floor line ends',
    manual_instr_corners: 'Click the four black corner squares, in any order. Each click is centred on its square.',
    manual_instr_floorline: 'Use this when a corner square is missing or damaged: click the two ends of the printed floor line, the end at the triangle first.',
    manual_count: '{n} of {total} points',
    manual_undo: 'Undo (Backspace)',
    manual_clear: 'Clear',
    manual_busy: 'Aligning…',
    manual_err_no_square: 'One point was not on a corner square and has been removed. Click that square again, or switch to the floor line ends.',
    manual_err_orientation: 'These points do not give a readable page. Check them, or switch to the floor line ends.',
    manual_confirm_first: 'Align the sheet first (or press D to score it later).',
    hint_manual_corners: 'Click the corner squares ({n} of 4) · Wheel: zoom · Drag: pan · Backspace: undo',
    hint_manual_floorline: 'Click the floor line ends, triangle end first ({n} of 2) · Wheel: zoom · Drag: pan · Backspace: undo',
    qr_after_manual: 'QR code read after manual alignment.',
    qr_code_taken: 'The QR code says {code}, but another scan in this session already has that code. Check the printed code.',
    timing: 'Processed in {ms} ms',

    sec_handles: 'Handles',
    h_head: 'Head',
    h_foot: 'Foot',
    h_ceiling: 'Ceiling',
    h_wall: 'Opposite wall',
    h_axis: 'Axis',
    st_suggested: 'suggested',
    st_snapped: 'snapped',
    st_manual: 'manual',
    st_auto: 'auto',
    st_unplaced: 'not placed',
    place: 'Place',
    replace: 'Re-place',
    foot_locked: 'Locked',
    foot_unlocked: 'Unlocked',
    foot_lock_title: 'The foot follows rule 3 unless you unlock it',

    sec_values: 'Values',
    v_figure: 'Figure',
    v_ceiling: 'Ceiling height',
    v_distance: 'Distance to wall',
    v_scale: 'Scale',
    v_est_v: 'Estimated ceiling height',
    v_est_h: 'Estimated distance',
    v_backup: 'to red bottom (backup)',
    v_est_v_axis: 'Estimated ceiling height, at the axis (backup)',
    v_est_h_floor: 'Estimated distance, at the floor (backup)',
    v_line_backup_title: 'Rules 1.2: the ceiling where its line crosses the figure axis, the wall where it stands on the floor, instead of the line averages',
    v_backup_title: 'Figure measured to the lowest red point instead of the floor line (rules 1.0 for floating figures)',
    v_figure_red: 'Figure to red bottom (backup)',
    unit_mm: 'mm',
    unit_m: 'm',
    unit_mm_per_m: 'mm/m',

    sec_flags: 'Flags',
    flag_red_not_found: 'Red figure not found',
    flag_figure_small: 'Figure smaller than the minimum',
    flag_figure_off_mark: 'Figure more than 5 mm from the start mark',
    flag_foot_off_floor: 'Red figure does not end on the floor line',
    flag_multiple_red: 'More than one red cluster',
    flag_axis_moved: 'Axis moved by hand',
    flag_manual_alignment: 'Manual alignment',
    flag_alignment_warning: 'Alignment warning',
    flag_ceiling_uneven: 'Ceiling line clearly slanted or uneven',
    flag_wall_uneven: 'Wall line clearly slanted or uneven',
    flag_color_noncompliant: 'Figure colour does not follow the instructions',
    flags_none: 'None',

    sec_view: 'View',
    view_contrast: 'Contrast boost (C)',
    view_mask: 'Show red mask (R)',
    view_guides: 'Guide lines (H)',
    view_snap: 'Snap',

    confirm: 'Confirm and download CSV',
    download_again: 'Download CSV again',
    missing: 'Still needed to confirm: {list}',
    need_rater_code: 'your rater code (Session, top of this panel)',
    confirmed: 'Confirmed at {time}. The CSV file was downloaded.',
    changed_after_confirm: 'Changed after confirming. Confirm again to download the new values.',

    err_corners_not_found: 'The four corner marks were not found.',
    err_orientation_failed: 'The page orientation could not be determined (floor line not found).',
    err_decode: 'This file could not be opened as an image.',
    err_type: 'Please choose a JPEG or PNG image.',
    err_internal: 'Something went wrong while processing the image: {msg}',

    // Navigation
    tab_score: 'Score',
    tab_sheets: 'Sheets',
    tab_project: 'New project',

    // Project card on the scoring screen
    sec_project: 'Project',
    project_none: 'No project file loaded: default settings (A4L, reference 1.70 m).',
    project_info: '{code}{title} · {template} · reference {ref} m',
    load_project: 'Load project file…',
    new_project: 'New project…',
    project_loaded_reload: 'Project loaded; the open image was analysed again with its settings.',
    project_rules_mismatch: 'This project file says scoring rules {file}; this tool uses rules {tool}.',
    project_bad_file: 'This is not a valid project file: {list}',
    sheet_code_qr: 'Read from the QR code on the sheet.',
    qr_template_mismatch: 'The QR code says template {qr}, but {used} is in use. Load the matching project file.',

    // Sheet generator
    sg_title: 'Sheet generator',
    sg_intro: 'Makes coded drawing sheets with a QR code. Nothing about the participant is printed on the front.',
    sg_template: 'Template',
    sg_template_locked: 'Set by the loaded project.',
    sg_label: 'Mark label',
    sg_count: 'Number of sheets',
    sg_exclude: 'Codes not to use',
    sg_exclude_placeholder: 'Paste codes already printed, or load an earlier code list',
    sg_load_list: 'Load code list…',
    sg_exclude_info: '{n} codes will be avoided.',
    sg_generate: 'Generate sheets',
    sg_bad_count: 'Enter a number of sheets between 1 and {max}.',
    sg_bad_label: 'The mark label must be 1 to 20 characters.',
    sg_done: '{n} sheets generated ({template}).',
    sg_print_warning: 'Print at 100% (actual size), not fit to page.',
    sg_check: 'Check one printed sheet with a ruler: the centres of the two top corner squares must be {mm} mm apart.',
    sg_print: 'Print…',
    sg_pdf: 'Download PDF',
    sg_csv: 'Download code list (CSV)',
    sg_codes: 'Codes: {list}',

    // New project form
    pf_title: 'New project',
    pf_intro: 'The project file is made once by the project owner and sent to every rater. It contains no personal data.',
    pf_code: 'Project code *',
    pf_code_help: 'Capital letters, digits and hyphens, e.g. VR3005.',
    pf_title_field: 'Title',
    pf_template: 'Template',
    pf_label: 'Mark label',
    pf_ref: 'Reference height (m)',
    pf_min_fig: 'Minimum figure (mm)',
    pf_foot_tol: 'Foot tolerance (mm)',
    pf_snap: 'Snap radius (mm)',
    pf_suggestions: 'Suggestions',
    pf_sug_figure: 'Head and foot from the red figure',
    pf_sug_ceiling: 'Ceiling (from Phase 2c)',
    pf_sug_wall: 'Opposite wall (from Phase 2c)',
    pf_exclusions: 'Exclusion criteria',
    pf_excl_add: 'Add criterion',
    pf_excl_remove: 'Remove',
    pf_excl_placeholder: 'Criterion, e.g. Figure not drawn',
    pf_rules: 'Scoring rules {v} (set by the tool).',
    pf_download: 'Download project file',
    pf_use: 'Use this project now',
    pf_saved: 'Project file downloaded: {name}',
    pf_errors: 'Please fix: {list}',
    pf_err_required: '{field} is required',
    pf_err_pattern: '{field} may contain only capital letters, digits and hyphens',
    pf_err_range: '{field} is out of range',
    pf_err_template: 'unknown template',
    pf_err_type: '{field} is not valid',
    pf_err_exclusion: 'an exclusion criterion is empty or repeated',
    pf_err_json: 'the file is not readable JSON',
    pf_err_not_project: 'the file is not a HuSS project file',
    pf_err_format_version: 'the project file format version is not supported',

    // Session (Phase 2b)
    mode: 'Mode *',
    mode_blind: 'Blind',
    mode_open: 'Open',
    mode_help: 'Blind hides file names, structures and computed numbers. The mode cannot change during a session.',
    choose_folder: 'Choose folder…',
    choose_files: 'Choose files…',
    open_scans: 'Open scans…',
    load_csv: 'Resume from CSV…',
    resume_loaded: 'CSV loaded ({file}): {n} records. They are applied when the scans are loaded.',
    resume_excel: 'This is the Excel view; it cannot be loaded back. Load the session CSV (the file without "_excel-view").',
    resume_bad: 'This CSV could not be read: {msg}',
    resume_other: 'This is not a HuSS measurement CSV.',
    resume_applied: 'Resumed: {n} records put back.',
    resume_conflicts: '{n} records belong to another rater or mode and were not used.',
    autosave_found: 'Resume the autosaved session: {done} of {total} done (saved {time}).',
    load_key: 'Load key table…',
    load_structures: 'Load structures table…',
    key_loaded: 'Key table: {n} sheets.',
    structures_loaded: 'Structures table: {n} structures.',
    table_errors: '{n} rows with problems (first: line {line}, {what}).',
    tbl_missing_columns: 'required columns missing',
    tbl_bad_sheet_code: 'invalid sheet code',
    tbl_duplicate: 'repeated',
    tbl_empty: 'empty cell',
    tbl_bad_number: 'not a positive number',
    need_rater_and_mode: 'Enter your rater code and choose Blind or Open first.',
    no_scans: 'No JPEG or PNG files were found.',
    reading_codes: 'Reading sheet codes {i} / {n}…',
    dup_title: 'The same sheet code appears in more than one scan',
    dup_text: 'Choose the scan to score for each code. The other scans are left out of this session.',
    dup_continue: 'Continue',
    session_summary: '{rater} · {mode} · {done} / {total} done',
    session_later: '{n} to review later',
    session_set_aside: '{n} scans left out (repeated sheet codes).',
    session_orphans: '{n} earlier records have no scan in this folder; they stay in the CSV.',
    download_csv: 'Download CSV',
    download_excel: 'Download for Excel',
    new_session: 'New session',
    new_session_confirm: 'Start a new session? Measurements not yet downloaded as CSV will be lost.',
    reminder_20: '{n} drawings confirmed since the last download. Please download the CSV.',
    reminder_done: 'All {n} drawings are done. Please download the CSV.',
    downloaded: 'CSV downloaded ({file}).',
    unload_warning: 'Some measurements have not been downloaded as CSV yet.',
    sheet_title: 'Sheet {code} · {pos} of {total}',
    sheet_title_unread: 'Sheet without a readable code {n} · {pos} of {total}',
    st_item_measured: 'measured',
    st_item_excluded: 'excluded',
    st_item_deferred: 'review later',
    sec_exclusion: 'Exclusion and notes',
    excl_other_label: 'Other reason (write it in the note)',
    nm_vertical: 'Vertical not measurable (no ceiling above the figure)',
    nm_horizontal: 'Horizontal not measurable (no opposite wall, or off the sheet)',
    note: 'Note',
    previous: 'Previous',
    review_later: 'Review later',
    confirm_next: 'Confirm and next',
    saved_status: 'Saved as {status}.',
    need_sheet_code: 'the sheet code (printed next to the QR square)',
    open_file: 'File: {file}',
    open_structure: 'Structure: {name} ({code}) · participant {participant}',
    open_not_in_key: 'This sheet code is not in the key table.',
    v_true_v: 'True ceiling height',
    v_true_h: 'True distance',
    v_e_v: 'E vertical',
    v_e_h: 'E horizontal',
    code_check: 'Same as the code printed on the sheet (K)',
    need_code_check: 'tick "Same as the code printed on the sheet"',
    code_picture: 'Printed code on this sheet',
    files_found: '{n} scans found.',
    files_ignored: '{n} other files ignored (e.g. the hidden .DS_Store file macOS keeps in folders).',
    finish_download: 'All done — Download CSV',
    tab_tables: 'Tables',
    tb_structures_title: 'Structures',
    tb_structures_intro: 'One row per building or room: its code, a name, and the true ceiling height and the true distance in metres. Used in Open mode and by Merge.',
    tb_col_code: 'Code',
    tb_col_name: 'Name',
    tb_col_true_v: 'True ceiling height (m)',
    tb_col_true_h: 'True distance (m)',
    tb_key_title: 'Key table',
    tb_key_intro: 'For the desk coordinator: which sheet belongs to which participant and structure, copied from the back of each sheet. Sheet codes are checked as you type. Press Enter in the last cell to add the next row.',
    tb_col_sheet: 'Sheet code',
    tb_col_participant: 'Participant code',
    tb_col_structure: 'Structure code',
    tb_add_structure: 'Add structure',
    tb_add_row: 'Add row',
    tb_import: 'Import CSV…',
    tb_download: 'Download CSV',
    tb_remove: 'Remove',
    tb_use: 'Use these tables in Open mode',
    tb_used: 'The tables are loaded for Open mode on the Score screen.',
    tb_st_count: '{n} structures.',
    tb_key_count: '{n} sheets, {bad} with problems.',
    tb_imported: 'Imported {n} rows.',
    tb_kept: 'Kept in this browser until you clear it; download the CSV to keep it safely.',
    tbl_unknown_structure: 'structure not in the structures table',
    tb_bad_number: 'not a positive number',
    tb_duplicate_code: 'repeated code',
    back_title: 'HuSS · desk coordinator record · do not scan',
    back_participant: 'Participant code',
    back_structure: 'Structure code',
    back_date: 'Date',
    back_coordinator: 'Coordinator',
    back_notes: 'Notes',
    sg_back: 'Print a back side for the desk coordinator (participant and structure codes, date). Needs double-sided printing: choose “flip on short edge”. Scan the front only.',
  };

  /** Interface text by key, with {placeholders} filled from params. */
  HUSS.t = function (key, params) {
    var s = HUSS.strings[key];
    if (s === undefined) return key;
    if (params) s = s.replace(/\{(\w+)\}/g, function (m, k) { return params[k] !== undefined ? params[k] : m; });
    return s;
  };

  if (typeof module === 'object' && module.exports) module.exports = HUSS.strings;
})(typeof globalThis !== 'undefined' ? globalThis : this);
