/* HuSS Scorer — js/strings.en.js
 * Every interface text. A translation is a copy of this file with the same keys.
 * Placeholders: {name}.
 */
(function (root) {
  'use strict';
  var HUSS = root.HUSS = root.HUSS || {};

  HUSS.strings = {
    app_title: 'HuSS Scorer',
    phase_badge: 'Phase 2 prototype',
    open_image: 'Open image…',

    drop_title: 'Drop a folder of scanned HuSS drawings here',
    drop_sub: 'JPEG or PNG, colour scans at 300 dpi. The images stay on this computer. Enter your rater code and choose a mode first.',
    drop_button: 'Choose folder…',
    drop_button_files: 'Choose files…',
    busy: 'Aligning and detecting…',

    fit: 'Fit',
    zoom_in: 'Zoom in (+)',
    zoom_out: 'Zoom out (−)',
    hint_idle: 'Wheel: zoom · Space + drag or drag empty paper: pan · 1–4: select handle · Arrows: nudge (Shift ×10) · Alt: no snap · Enter: confirm',
    hint_place: 'Click on the drawing to place the {name} handle. Esc cancels.',
    hint_foot_locked: 'The foot handle is locked. Unlock it in the panel to move it.',

    sec_session: 'Session',
    project_code: 'Project code',
    rater_code: 'Rater code *',
    rater_code_placeholder: 'your initials, e.g. EY',
    rater_code_help: 'Who is scoring: your initials or a short code. Required; it is written into the CSV.',
    sheet_code: 'Sheet code',
    sheet_code_placeholder: 'e.g. 6QHJ4',
    sheet_code_hint: 'The QR code could not be read: type the 5 characters printed next to the QR square (see the picture).',
    sheet_code_ok: 'Check character OK',
    sheet_code_bad: 'Not a sheet code. Copy the 5 characters printed at the bottom right, next to the QR square (they never contain 0, 1, I, O or S).',

    sec_image: 'Image',
    no_image: 'No image loaded.',
    align_summary: 'Aligned automatically · {r} px/mm · residual {res} mm · rotation {rot}°',
    align_summary_auto_three_corners: 'Aligned automatically from three corner marks (one is missing) · {r} px/mm · residual {res} mm · rotation {rot}°',
    align_summary_manual_corners: 'Aligned by hand (corner squares) · {r} px/mm · residual {res} mm · rotation {rot}°',
    align_summary_manual_floorline: 'Aligned by hand (floor line ends) · {r} px/mm · rotation {rot}°',

    // Manual alignment (spec 7.5)
    sec_manual: 'Manual alignment',
    manual_why_corners_not_found: 'The corner marks of this sheet could not be found automatically. Align it by hand, then score it as usual.',
    manual_why_orientation_failed: 'The page orientation could not be found automatically. Align it by hand, then score it as usual.',
    manual_method_corners: '4 corner squares',
    manual_method_floorline: '2 floor line ends',
    manual_instr_corners: 'Click the four black corner squares, in any order. Each click is centred on its square.',
    manual_instr_floorline: 'Use this when a corner square is missing or damaged: click the two ends of the printed floor line, the end at the triangle first.',
    manual_count: '{n} of {total} points',
    manual_undo: 'Undo (Backspace)',
    manual_clear: 'Clear',
    manual_busy: 'Aligning…',
    manual_err_no_square: 'One point was not on a corner square and has been removed. Click that square again, or switch to the floor line ends.',
    manual_err_orientation: 'These points do not give a readable page. Check them, or switch to the floor line ends.',
    manual_confirm_first: 'Align the sheet first (or press D to score it later).',
    hint_manual_corners: 'Click the corner squares ({n} of 4) · Wheel: zoom · Drag: pan · Backspace: undo',
    hint_manual_floorline: 'Click the floor line ends, triangle end first ({n} of 2) · Wheel: zoom · Drag: pan · Backspace: undo',
    qr_after_manual: 'Sheet code read after manual alignment.',
    qr_code_taken: 'The QR code says {code}, but another scan in this session already has that code. Check the printed code.',
    timing: 'Processed in {ms} ms',

    sec_handles: 'Handles',
    h_head: 'Head',
    h_foot: 'Foot',
    h_ceiling: 'Ceiling',
    h_wall: 'Opposite wall',
    h_axis: 'Axis',
    st_suggested: 'suggested',
    st_snapped: 'snapped',
    st_manual: 'manual',
    st_auto: 'auto',
    st_unplaced: 'not placed',
    place: 'Place',
    replace: 'Re-place',
    foot_locked: 'Locked',
    foot_unlocked: 'Unlocked',
    foot_lock_title: 'The foot follows rule 3 unless you unlock it',

    sec_values: 'Values',
    v_figure: 'Figure',
    v_ceiling: 'Ceiling height',
    v_distance: 'Distance to wall',
    v_scale: 'Scale',
    v_est_v: 'Estimated ceiling height',
    v_est_h: 'Estimated distance',
    v_backup: 'to red bottom (backup)',
    v_est_v_axis: 'Estimated ceiling height, at the axis (backup)',
    v_est_h_floor: 'Estimated distance, at the floor (backup)',
    v_line_backup_title: 'Rules 1.2: the ceiling where its line crosses the figure axis, the wall where it stands on the floor, instead of the line averages',
    v_backup_title: 'Figure measured to the lowest red point instead of the floor line (rules 1.0 for floating figures)',
    v_figure_red: 'Figure to red bottom (backup)',
    unit_mm: 'mm',
    unit_m: 'm',
    unit_mm_per_m: 'mm/m',

    sec_flags: 'Flags',
    flag_red_not_found: 'Red figure not found',
    flag_figure_small: 'Figure smaller than the minimum',
    flag_figure_off_mark: 'Figure more than 5 mm from the start mark',
    flag_foot_off_floor: 'Red figure does not end on the floor line',
    flag_multiple_red: 'More than one red cluster',
    flag_axis_moved: 'Axis moved by hand',
    flag_manual_alignment: 'Manual alignment',
    flag_alignment_warning: 'Alignment warning',
    flag_ceiling_uneven: 'Ceiling line clearly slanted or uneven',
    flag_wall_uneven: 'Wall line clearly slanted or uneven',
    flag_color_noncompliant: 'Figure colour does not follow the instructions',
    flags_none: 'None',

    sec_view: 'View',
    view_contrast: 'Contrast boost (C)',
    view_mask: 'Show red mask (R)',
    view_guides: 'Guide lines (H)',
    view_snap: 'Snap',

    confirm: 'Confirm and download CSV',
    download_again: 'Download CSV again',
    missing: 'Still needed to confirm: {list}',
    need_rater_code: 'your rater code (Session, top of this panel)',
    confirmed: 'Confirmed at {time}. The CSV file was downloaded.',
    changed_after_confirm: 'Changed after confirming. Confirm again to download the new values.',

    err_corners_not_found: 'The four corner marks were not found.',
    err_orientation_failed: 'The page orientation could not be determined (floor line not found).',
    err_decode: 'This file could not be opened as an image.',
    err_type: 'Please choose a JPEG or PNG image.',
    err_internal: 'Something went wrong while processing the image: {msg}',

    // Navigation
    tab_score: 'Score',
    tab_sheets: 'Sheets',
    tab_project: 'New project',

    // Project card on the scoring screen
    sec_project: 'Project',
    project_none: 'No project file loaded: default settings (A4L, reference 1.70 m).',
    project_info: '{code}{title} · {template} · reference {ref} m',
    load_project: 'Load project file…',
    new_project: 'New project…',
    project_loaded_reload: 'Project loaded; the open image was analysed again with its settings.',
    project_rules_mismatch: 'This project file says scoring rules {file}; this tool uses rules {tool}.',
    project_bad_file: 'This is not a valid project file: {list}',
    sheet_code_qr: 'Read from the QR code on the sheet.',
    sheet_code_ocr: 'Read from the printed characters (the QR code could not be read). Compare it with the picture; correct it if needed.',
    qr_template_mismatch: 'The QR code says template {qr}, but {used} is in use. Load the matching project file.',

    // Sheet generator
    sg_title: 'Sheet generator',
    sg_intro: 'Makes coded drawing sheets with a QR code. Nothing about the participant is printed on the front.',
    sg_template: 'Template',
    sg_template_locked: 'Set by the loaded project.',
    sg_label: 'Mark label',
    sg_count: 'Number of sheets',
    sg_exclude: 'Codes not to use',
    sg_exclude_placeholder: 'Paste codes already printed, or load an earlier code list',
    sg_load_list: 'Load code list…',
    sg_exclude_info: '{n} codes will be avoided.',
    sg_generate: 'Generate sheets',
    sg_bad_count: 'Enter a number of sheets between 1 and {max}.',
    sg_bad_label: 'The mark label must be 1 to 20 characters.',
    sg_done: '{n} sheets generated ({template}).',
    sg_print_warning: 'Print at 100% (actual size), not fit to page.',
    sg_check: 'Check one printed sheet with a ruler: the centres of the two top corner squares must be {mm} mm apart.',
    sg_print: 'Print…',
    sg_pdf: 'Download PDF',
    sg_csv: 'Download code list (CSV)',
    sg_codes: 'Codes: {list}',

    // New project form
    pf_title: 'New project',
    pf_intro: 'The project file is made once by the project owner and sent to every rater. It contains no personal data.',
    pf_code: 'Project code *',
    pf_code_help: 'Capital letters, digits and hyphens, e.g. VR3005.',
    pf_title_field: 'Title',
    pf_template: 'Template',
    pf_label: 'Mark label',
    pf_ref: 'Reference height (m)',
    pf_min_fig: 'Minimum figure (mm)',
    pf_foot_tol: 'Foot tolerance (mm)',
    pf_snap: 'Snap radius (mm)',
    pf_suggestions: 'Suggestions',
    pf_sug_figure: 'Head and foot from the red figure',
    pf_sug_ceiling: 'Ceiling (from Phase 2c)',
    pf_sug_wall: 'Opposite wall (from Phase 2c)',
    pf_exclusions: 'Exclusion criteria',
    pf_excl_add: 'Add criterion',
    pf_excl_remove: 'Remove',
    pf_excl_placeholder: 'Criterion, e.g. Figure not drawn',
    pf_rules: 'Scoring rules {v} (set by the tool).',
    pf_download: 'Download project file',
    pf_use: 'Use this project now',
    pf_saved: 'Project file downloaded: {name}',
    pf_errors: 'Please fix: {list}',
    pf_err_required: '{field} is required',
    pf_err_pattern: '{field} may contain only capital letters, digits and hyphens',
    pf_err_range: '{field} is out of range',
    pf_err_template: 'unknown template',
    pf_err_type: '{field} is not valid',
    pf_err_exclusion: 'an exclusion criterion is empty or repeated',
    pf_err_json: 'the file is not readable JSON',
    pf_err_not_project: 'the file is not a HuSS project file',
    pf_err_format_version: 'the project file format version is not supported',

    // Session (Phase 2b)
    mode: 'Mode *',
    mode_blind: 'Blind',
    mode_open: 'Open',
    mode_help: 'Blind hides file names, structures and computed numbers. The mode cannot change during a session.',
    choose_folder: 'Choose folder…',
    choose_files: 'Choose files…',
    open_scans: 'Open scans…',
    load_csv: 'Resume from CSV…',
    resume_loaded: 'CSV loaded ({file}): {n} records. They are applied when the scans are loaded.',
    resume_excel: 'This is the Excel view; it cannot be loaded back. Load the session CSV (the file without "_excel-view").',
    resume_bad: 'This CSV could not be read: {msg}',
    resume_other: 'This is not a HuSS measurement CSV.',
    resume_applied: 'Resumed: {n} records put back.',
    resume_conflicts: '{n} records belong to another rater or mode and were not used.',
    autosave_found: 'Resume the autosaved session: {done} of {total} done (saved {time}).',
    load_key: 'Load key table…',
    load_structures: 'Load structures table…',
    key_loaded: 'Key table: {n} sheets.',
    structures_loaded: 'Structures table: {n} structures.',
    table_errors: '{n} rows with problems (first: line {line}, {what}).',
    tbl_missing_columns: 'required columns missing',
    tbl_bad_sheet_code: 'invalid sheet code',
    tbl_duplicate: 'repeated',
    tbl_empty: 'empty cell',
    tbl_bad_number: 'not a positive number',
    need_rater_and_mode: 'Enter your rater code and choose Blind or Open first.',
    no_scans: 'No JPEG or PNG files were found.',
    reading_codes: 'Reading sheet codes {i} / {n}…',
    dup_title: 'The same sheet code appears in more than one scan',
    dup_text: 'Choose the scan to score for each code. The other scans are left out of this session.',
    dup_continue: 'Continue',
    session_summary: '{rater} · {mode} · {done} / {total} done',
    session_later: '{n} to review later',
    session_set_aside: '{n} scans left out (repeated sheet codes).',
    session_orphans: '{n} earlier records have no scan in this folder; they stay in the CSV.',
    download_csv: 'Download CSV',
    download_excel: 'Download for Excel',
    new_session: 'New session',
    new_session_confirm: 'Start a new session? Measurements not yet downloaded as CSV will be lost.',
    reminder_20: '{n} drawings confirmed since the last download. Please download the CSV.',
    reminder_done: 'All {n} drawings are done. Please download the CSV.',
    downloaded: 'CSV downloaded ({file}).',
    unload_warning: 'Some measurements have not been downloaded as CSV yet.',
    sheet_title: 'Sheet {code} · {pos} of {total}',
    sheet_title_unread: 'Sheet without a readable code {n} · {pos} of {total}',
    st_item_measured: 'measured',
    st_item_excluded: 'excluded',
    st_item_deferred: 'review later',
    sec_exclusion: 'Exclusion and notes',
    excl_other_label: 'Other reason (write it in the note)',
    nm_vertical: 'Vertical not measurable (no ceiling above the figure)',
    nm_horizontal: 'Horizontal not measurable (no opposite wall, or off the sheet)',
    note: 'Note',
    previous: 'Previous',
    review_later: 'Review later',
    confirm_next: 'Confirm and next',
    saved_status: 'Saved as {status}.',
    need_sheet_code: 'the sheet code (printed next to the QR square)',
    open_file: 'File: {file}',
    open_structure: 'Structure: {name} ({code}) · participant {participant}',
    open_not_in_key: 'This sheet code is not in the key table.',
    v_true_v: 'True ceiling height',
    v_true_h: 'True distance',
    v_e_v: 'E vertical',
    v_e_h: 'E horizontal',
    code_check: 'Same as the code printed on the sheet (K)',
    need_code_check: 'tick "Same as the code printed on the sheet"',
    code_picture: 'Printed code on this sheet',
    files_found: '{n} scans found.',
    files_ignored: '{n} other files ignored (e.g. the hidden .DS_Store file macOS keeps in folders).',
    finish_download: 'All done — Download CSV',
    tab_tables: 'Tables',
    tb_structures_title: 'Structures',
    tb_structures_intro: 'One row per building or room: its code, a name, and the true ceiling height and the true distance in metres. Used in Open mode and by Merge.',
    tb_col_code: 'Code',
    tb_col_name: 'Name',
    tb_col_true_v: 'True ceiling height (m)',
    tb_col_true_h: 'True distance (m)',
    tb_key_title: 'Key table',
    tb_key_intro: 'For the desk coordinator: which sheet belongs to which participant and structure, copied from the back of each sheet. Sheet codes are checked as you type. Press Enter in the last cell to add the next row.',
    tb_col_sheet: 'Sheet code',
    tb_col_participant: 'Participant code',
    tb_col_structure: 'Structure code',
    tb_add_structure: 'Add structure',
    tb_add_row: 'Add row',
    tb_import: 'Import CSV…',
    tb_download: 'Download CSV',
    tb_remove: 'Remove',
    tb_use: 'Use these tables in Open mode',
    tb_used: 'The tables are loaded for Open mode on the Score screen.',
    tb_st_count: '{n} structures.',
    tb_key_count: '{n} sheets, {bad} with problems.',
    tb_imported: 'Imported {n} rows.',
    tb_kept: 'Kept in this browser until you clear it; download the CSV to keep it safely.',
    tbl_unknown_structure: 'structure not in the structures table',
    tb_bad_number: 'not a positive number',
    tb_duplicate_code: 'repeated code',
    back_title: 'HuSS · desk coordinator record · do not scan',
    back_participant: 'Participant code',
    back_structure: 'Structure code',
    back_date: 'Date',
    back_coordinator: 'Coordinator',
    back_notes: 'Notes',
// Results screen: Merge and Report (spec 8.6; Report beyond the v1 spec)
    tab_results: 'Results',
    res_title: 'Results',
    res_warning: 'This screen shows true dimensions and errors. In a blind study, raters open it only after all scoring is finished.',
    res_files: 'Measurement files',
    res_files_help: 'One or more measurement CSVs (Download CSV on the Score screen), from one or more raters. A merged CSV can be opened here too.',
    res_add: 'Add CSV files…',
    res_clear: 'Remove all',
    res_none: 'No files yet.',
    res_file_line: '{name}: {n} records · rater {raters} · project {projects}',
    res_remove: 'Remove',
    res_bad_file: '{name}: {why}',
    res_err_excel: 'this is the Excel view, which cannot be read back; use the file from Download CSV',
    res_err_not: 'not a HuSS measurement CSV',
    res_err_parse: 'the file could not be read ({detail})',
    res_tables: 'Key and structures',
    res_tables_help: 'The key table tells which participant drew each sheet and which structure it shows; the structures table gives the true dimensions.',
    res_tables_screen: 'From the Tables screen: {s} structures, {k} key rows.',
    res_tables_files: 'From files: {s} structures, {k} key rows.',
    res_tables_none: 'None loaded: errors (E) cannot be computed without them.',
    res_load_key: 'Load key CSV…',
    res_table_errors: '{name}: {n} rows with problems were left out.',
    res_load_structures: 'Load structures CSV…',
    res_use_screen: 'Use the Tables screen',
    res_merged: 'Merged: {n} records ({m} measured, {e} excluded).',
    res_dl_merged: 'Download merged CSV',
    res_dl_excel: 'Download for Excel',
    res_report: 'Report',
    res_rater: 'Rater',
    res_method: 'Values',
    res_all_raters: 'All raters',
    res_print: 'Print / save as PDF',
    res_dl_html: 'Download report (HTML)',
    res_svg: 'SVG',
    res_png: 'PNG',
    res_empty: 'Add measurement files to see the report.',

    // Report
    rp_card_drawings: 'Drawings',
    rp_card_records: '{n} records (several raters)',
    rp_card_measured: 'Measured / excluded',
    rp_card_nm: 'Not measurable: height {v}, distance {h}',
    rp_card_participants: 'Participants',
    rp_card_struct_raters: 'Structures: {s} · raters: {r}',
    rp_card_ev: 'Ceiling height: median error',
    rp_card_eh: 'Distance: median error',
    rp_card_e_sub: 'n = {n} · {over} overestimate · middle half {iqr}',
    rp_no_values: 'No values yet',
    rp_no_structure: 'No structure',
    rp_ch_e_struct_v: 'Error in ceiling height, by structure',
    rp_ch_e_struct_h: 'Error in distance to the wall, by structure',
    rp_ax_e_v: 'E ceiling height',
    rp_ax_e_h: 'E distance',
    rp_cap_e_struct: 'Each dot is one drawing. Box: the middle half of the drawings; thick line: the median. Above 0 overestimated, below 0 underestimated.',
    rp_ch_est_true_v: 'Estimated against true ceiling height',
    rp_ch_est_true_h: 'Estimated against true distance',
    rp_ax_true_v: 'True ceiling height (m)',
    rp_ax_est_v: 'Estimated ceiling height (m)',
    rp_ax_true_h: 'True distance (m)',
    rp_ax_est_h: 'Estimated distance (m)',
    rp_identity: 'estimate = true',
    rp_cap_est_true: 'Dots above the dashed line are overestimates, dots below it underestimates.',
    rp_ch_e_v_h: 'Error in height against error in distance',
    rp_q_tl: 'height over, distance under',
    rp_q_tr: 'both over',
    rp_q_bl: 'both under',
    rp_q_br: 'height under, distance over',
    rp_cap_e_v_h: 'Each dot is one drawing: do those who overestimate the height also overestimate the depth?',
    rp_ch_hist_v: 'Distribution of the error in ceiling height',
    rp_ch_hist_h: 'Distribution of the error in distance',
    rp_ax_drawings: 'Drawings',
    rp_cap_hist: 'Dashed line: no error.',
    rp_pl_suggested: 'Suggestion kept',
    rp_pl_snapped: 'Moved onto a line',
    rp_pl_manual: 'Placed by hand',
    rp_pl_none: 'Not placed',
    rp_ch_handles: 'How the handles ended up',
    rp_cap_handles: '“Suggestion kept”: the rater accepted the tool’s suggestion unchanged.',
    rp_ch_flags: 'Flags',
    rp_cap_flags: 'Share of records with each flag.',
    rp_ch_code_source: 'Where the sheet codes came from',
    rp_cap_sources: 'QR code, the printed characters next to it, or typed by the rater.',
    rp_src_qr: 'QR code',
    rp_src_ocr: 'Printed characters',
    rp_src_manual: 'Typed by the rater',
    rp_src_none: 'No code',
    rp_ch_align: 'Alignment',
    rp_al_auto: 'Automatic',
    rp_al_auto_three_corners: 'Automatic, three corner marks',
    rp_al_manual_corners: 'By hand, corner squares',
    rp_al_manual_floorline: 'By hand, floor line ends',
    rp_ch_duration: 'Time per drawing',
    rp_ax_seconds: 'Seconds',
    rp_cap_duration: 'Median {median} s per drawing.',
    rp_t_structure: 'Structure',
    rp_t_true_v: 'True height (m)',
    rp_t_est_v: 'Est. height (m), mean (median)',
    rp_t_e_v: 'E height, median [middle half]',
    rp_t_over: 'Over',
    rp_t_true_h: 'True distance (m)',
    rp_t_est_h: 'Est. distance (m), mean (median)',
    rp_t_e_h: 'E distance, median [middle half]',
    rp_t_handle: 'Handle',
    rp_t_offered: 'Suggested',
    rp_t_accepted: 'Kept unchanged',
    rp_checks: 'Data checks',
    rp_checks_ok: 'No problems: every record has a key row and a structure.',
    rp_p_no_key: 'No key table loaded: participants, structures and errors are unknown.',
    rp_p_no_structures: 'No structures table loaded: the true dimensions, and so the errors, are unknown.',
    rp_p_mixed: 'More than one project code: {list}.',
    rp_p_not_in_key: '{n} sheets are not in the key table: {list}.',
    rp_p_missing_structure: '{n} sheets have a structure missing from the structures table: {list}.',
    rp_p_duplicates: '{n} sheets were scored twice by the same rater; the later record is used: {list}.',
    rp_p_unfinished: '{n} records are not finished (review later) and are left out: {list}.',
    rp_p_not_measured: '{n} sheets of the key table have no record: {list}.',
    rp_sec_results: 'Results',
    rp_sec_structures: 'By structure',
    rp_sec_quality: 'Scoring quality',
    rp_sec_acceptance: 'Suggestions',
    rp_no_true: 'No true dimensions: load the key table and the structures table to see the errors.',
    rp_meta: 'Projects: {projects} · Rater: {rater} · Values: {method} · Made {date} with HuSS Scorer {tool}, rules {rules}',
    rp_all_raters: 'all',
    rp_method_main: 'line averages (rules 1.3)',
    rp_method_points: 'ceiling at the axis, wall at the floor (rules 1.2)',
    rp_method_red: 'figure to the lowest red point',
    rp_doc_title: 'HuSS report · {projects}',
    rp_footer: 'E = (estimate − true) / true. Descriptive statistics only; ICC and kappa are computed with r/icc_kappa.R.',

    // Calibration sheets and check (spec 10.3)
    sg_calibration: 'Calibration sheets: a red figure, a ceiling and walls of known size are printed on them, in ten layouts (print in colour, at 100 %). Score them like drawings, then check them on the Results screen with the calibration key.',
    sg_cal_key: 'Download calibration key',
    sg_cal_done: '{n} calibration sheets ({template}). Keep the calibration key: it holds the printed lengths.',
    cal_title: 'Calibration check',
    cal_help: 'For printed calibration sheets: load the calibration key from the Sheets screen; the measured lengths are compared with the printed ones (at most 0.3 mm or 1 % off).',
    cal_load: 'Load calibration key…',
    cal_bad: '{name} is not a calibration key.',
    cal_summary: '{passed} of {n} calibration sheets within 0.3 mm or 1 % on all three lengths.',
    cal_not_scored: 'Not scored yet: {list}.',
    cal_t_rater: 'Rater',
    cal_t_layout: 'Layout',
    cal_t_figure_mm: 'Figure (mm), measured / printed',
    cal_t_ceiling_mm: 'Ceiling (mm), measured / printed',
    cal_t_distance_mm: 'Distance (mm), measured / printed',
    cal_t_diff: 'Difference',
    cal_t_result: 'Result',
    cal_pass: 'within',
    cal_fail: 'outside',

    // Compare screen (spec 8.7) and subsample lists (spec 5.4, 8.1)
    tab_compare: 'Compare',
    cmp_title: 'Compare two raters',
    cmp_intro: 'Read only: the records of two raters side by side. Add their CSV files (or one merged CSV holding both), then choose the two raters.',
    cmp_r1: 'Rater 1',
    cmp_r2: 'Rater 2',
    cmp_need_two: 'Add files with at least two raters.',
    cmp_dl_wide: 'Download comparison CSV',
    cmp_dl_html: 'Download comparison (HTML)',
    cmp_tables_note: 'Errors (E) come from a merged CSV or, for plain files, from the key and structures chosen on the Results screen.',
    ss_title: 'Subsample list for a second rater',
    ss_intro: 'A random choice of sheet codes from the files above (rater 1’s sheets). The second rater loads the list on the Score screen.',
    ss_count: 'How many',
    ss_percent: 'or percent',
    ss_by_structure: 'The same share from every structure',
    ss_make: 'Make and download list',
    ss_made: '{n} of {total} sheet codes chosen.',
    ss_none: 'No sheets to choose from yet.',
    load_subsample: 'Subsample list…',
    subsample_loaded: 'Subsample list {file}: {n} sheet codes; only these will be scored.',
    subsample_bad: 'Subsample list {file}: {n} lines are not sheet codes and were skipped.',
    subsample_applied: 'Subsample: {found} of {n} sheets found; {left} other scans left out.',
    subsample_missing: 'Not in the folder: {list}.',
    cp_card_matched: 'Drawings scored by both',
    cp_card_only: 'only {a}: {na} · only {b}: {nb}',
    cp_card_d_v: 'Ceiling height: difference',
    cp_card_d_h: 'Distance: difference',
    cp_card_d_sub: 'mean ± SD of (rater 2 − rater 1) / mean, n = {n}',
    cp_card_excl: 'Same exclusion decision',
    cp_card_nm: 'Same “not measurable”: height {v}, distance {h}',
    cp_sec_agreement: 'Agreement',
    cp_sec_table: 'Side by side',
    cp_ch_ba_v: 'Agreement of the raters: ceiling height',
    cp_ch_ba_h: 'Agreement of the raters: distance',
    cp_ax_mean_e_v: 'Mean of the two raters’ E (ceiling height)',
    cp_ax_mean_e_h: 'Mean of the two raters’ E (distance)',
    cp_ax_mean_est_v: 'Mean of the two estimates (m)',
    cp_ax_mean_est_h: 'Mean of the two estimates (m)',
    cp_ax_diff_e: 'E {r2} − E {r1}',
    cp_ax_reldiff: '({r2} − {r1}) / mean',
    cp_cap_ba_e: 'Each dot is one drawing. Red line: the mean difference ({r2} − {r1}); dashed: 95 % limits of agreement (mean ± 1.96 SD).',
    cp_cap_ba_est: 'Each dot is one drawing: relative difference of the estimates. Red line: the mean difference ({r2} − {r1}); dashed: 95 % limits of agreement.',
    cp_icc_note: 'ICC(2,1) and Cohen’s kappa are not computed here: download the comparison CSV and run r/icc_kappa.R.',
    cp_only_list: 'Only {a}: {la}. Only {b}: {lb}.',
    cp_t_sheet: 'Sheet',
    cp_t_participant: 'Participant',
    cp_t_v: 'Height {r} (m)',
    cp_t_h: 'Distance {r} (m)',
    cp_t_diff: 'Difference',
    cp_t_dec: 'Decision {r}',
    cp_dec_measured: 'measured',
    cp_dec_excluded: 'excluded',
    cp_dec_nm_v: 'height not measurable',
    cp_dec_nm_h: 'distance not measurable',
    cp_dec_nm_v_nm_h: 'neither measurable',
    cp_doc_title: 'HuSS comparison · {r1} and {r2}',

    sg_back: 'Print a back side for the desk coordinator (participant and structure codes, date). Needs double-sided printing: choose “flip on short edge”. Scan the front only.',
  };

  /** Interface text by key, with {placeholders} filled from params. */
  HUSS.t = function (key, params) {
    var s = HUSS.strings[key];
    if (s === undefined) return key;
    if (params) s = s.replace(/\{(\w+)\}/g, function (m, k) { return params[k] !== undefined ? params[k] : m; });
    return s;
  };

  if (typeof module === 'object' && module.exports) module.exports = HUSS.strings;
})(typeof globalThis !== 'undefined' ? globalThis : this);
