// Developer tool: the example scans behind "Try with example scans" on the main menu.
//
//   node tests/tools/make-demo.js [folder]     (macOS: uses sips to recompress the JPEGs)
//
// Takes the twenty demonstration scans (default: test_scans/Demonstration, kept out of the
// repository) of a two-structure project, drawn by the author, keeps them at 300 dpi but
// recompresses them (at lower resolutions some QR codes and suggestions came out differently)
// (for each scan the lowest JPEG quality that the tool reads exactly as the original scan) and
// writes demo/demo-scans.js: a classic script (works when index.html is opened from disk,
// unlike fetch) that sets HUSS.demoData = { project, credit, scans: [{ name, data (base64 JPEG) }] }.
// The main menu loads it only when the example is chosen. These are the only scans in the
// repository.
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..', '..');
const SRC = process.argv[2] ? path.resolve(process.argv[2]) : path.join(ROOT, 'test_scans', 'Demonstration');
const OUT = path.join(ROOT, 'demo');
const MAX_PX = 3508;   // A4 long side at 300 dpi: the scans as they were made
const QUALITIES = [40, 50, 60, 70, 80, 90]; // tried in turn for each scan

const CREDIT = 'All drawings, these examples and every drawing used in developing the tool, were made by the author, Erdem Yıldırım.';

// What some sheets show (by sheet code); every sheet has its structure box marked.
const NOTES = {
  '8JK9T': 'ceiling slab and wall drawn thick and hatched: measured at the underside and at the inner face (rules 1.5)'
};

const project = {
  format: 'huss-project', format_version: 2, project_code: 'HUSS-EXAMPLE',
  title: 'Example scans: twenty drawings of two structures by the author',
  template: 'A4L', sheet_label: 'figure', ref_height_m: 1.7, min_figure_mm: 10, foot_tolerance_mm: 4, snap_radius_mm: 1.5,
  suggestions: { figure: true, ceiling: true, wall: true },
  exclusion_criteria: [
    { id: 'excl_no_figure', label: 'Figure not drawn' },
    { id: 'excl_not_standing_full', label: 'Figure not standing or not full height' },
    { id: 'excl_not_along_axis', label: 'Section not drawn along the viewing axis' }
  ],
  // the codes printed under the boxes of the example sheets
  structures: [
    { code: 'S1', name: 'Room S1 (3 m / 6 m)', true_vertical_m: 3, true_horizontal_m: 6 },
    { code: 'S2', name: 'Room S2 (7 m / 14 m)', true_vertical_m: 7, true_horizontal_m: 14 }
  ],
  rules_version: '1.5', created_at: '2026-10-09T12:00:00+03:00'
};

const HUSS = require('../unit/_load.js');
const src = fs.readFileSync(path.join(__dirname, 'inspect.js'), 'utf8');
const readBmp = new Function('fs', src.match(/function readBmp[\s\S]*?\n}\n/)[0] + 'return readBmp;')(fs);

fs.mkdirSync(OUT, { recursive: true });
const files = fs.readdirSync(SRC).filter((f) => /\.jpe?g$/i.test(f)).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
const tmp = path.join(os.tmpdir(), 'huss-demo.jpeg'), bmp = path.join(os.tmpdir(), 'huss-demo.bmp');
const prm = HUSS.io.project.paramsOf(HUSS.io.project.validate(JSON.parse(JSON.stringify(project))).project);
/** What the tool reads from a JPEG file: code, box, estimates (to compare recompressed with original). */
function reading(jpeg) {
  execFileSync('sips', ['-s', 'format', 'bmp', jpeg, '--out', bmp], { stdio: 'ignore' });
  const a = HUSS.detect.pipeline.analyze(readBmp(bmp), { template: 'A4L', params: prm });
  if (!a.ok) return { code: '?', box: null, est: [null, null] };
  const s = a.suggestions;
  const c = HUSS.measure.compute.compute({ head_y: s.head_y, foot_y: s.foot_y, ceiling_y: s.ceiling_y, wall_x: s.wall_x, axis_x: s.axis_x, floor_y_axis: HUSS.detect.pipeline.floorY(a, s.axis_x) }, prm);
  return { code: a.qr.found ? a.qr.sheet_code : '?', box: HUSS.detect.boxes.codeOf(a.boxes, project.structures), est: [c.est_vertical_m, c.est_horizontal_m] };
}
const same = (p, q) => p.code === q.code && p.box === q.box && p.est.every((v, k) => (v == null) === (q.est[k] == null) && (v == null || Math.abs(v - q.est[k]) <= 0.005 * v));
const scans = files.map((file, i) => {
  const original = reading(path.join(SRC, file));
  let q, r;
  for (q of QUALITIES) {
    execFileSync('sips', ['-Z', String(MAX_PX), '-s', 'formatOptions', String(q), path.join(SRC, file), '--out', tmp], { stdio: 'ignore' });
    r = reading(tmp);
    if (same(r, original)) break;
  }
  if (!same(r, original)) console.warn('  ' + file + ': read differently even at quality ' + q);
  const data = fs.readFileSync(tmp).toString('base64');
  return { name: 'example-' + String(i + 1).padStart(2, '0') + '.jpeg', from: file, code: r.code, box: r.box, note: NOTES[r.code] || '', data, est: r.est, quality: q };
});
const js = '/* HuSS Scorer — demo/demo-scans.js: example scans for "Try with example scans".\n' +
  ' * Generated by tests/tools/make-demo.js; do not edit. ' + CREDIT + '\n' +
  ' * Loaded only when the example is chosen on the main menu. */\n' +
  '(function (root) {\n  \'use strict\';\n  var HUSS = root.HUSS = root.HUSS || {};\n  HUSS.demoData = ' +
  JSON.stringify({ project, credit: CREDIT, scans: scans.map(({ name, data }) => ({ name, data })) }) +
  ';\n})(typeof globalThis !== \'undefined\' ? globalThis : this);\n';
fs.writeFileSync(path.join(OUT, 'demo-scans.js'), js);
const readme = '# Example scans\n\n' + CREDIT + '\n\n' +
  '`demo-scans.js` holds twenty scanned drawings (300 dpi, recompressed) and an example project with **two structures**: S1 (ceiling 3 m, opposite wall 6 m) and S2 (ceiling 7 m, opposite wall 14 m). Each sheet has the structure boxes, and the desk coordinator marked the one drawn. Main menu → **Try with example scans** loads them and starts an Open mode session (rater code DEMO); nothing is uploaded.\n\n' +
  '**Different structures.** The structure of each sheet comes from its marked box: in Open mode it is shown under the sheet code (and can be changed from the list there). The **Tables** screen lists every scored sheet with the structure of its box; change it there where a box was marked wrongly (your row is used instead of the box). Results then shows the errors by structure.\n\n' +
  'Made with `node tests/tools/make-demo.js` from the original scans (not in the repository).\n\n| File | Sheet code | Box | Shows |\n|---|---|---|---|\n' +
  scans.map((s) => '| ' + s.name + ' | ' + s.code + ' | ' + (s.box || '–') + ' | ' + s.note + ' |').join('\n') + '\n';
fs.writeFileSync(path.join(OUT, 'README.md'), readme);
const f2 = (v) => v == null ? '-' : v.toFixed(2);
console.log('demo/demo-scans.js', Math.round(js.length / 1024) + ' KB', scans.length + ' scans');
scans.forEach((s) => console.log(' ', s.name, s.from, s.code, s.box, f2(s.est[0]), f2(s.est[1]), 'q' + s.quality));
