// Developer tool: the example scans behind "Try with example scans" on the main menu.
//
//   node tests/tools/make-demo.js        (macOS: uses sips to scale the JPEGs)
//
// Takes ten trial 3 scans from samples/real, scales them to 150 dpi (JPEG quality 70) and writes
// demo/demo-scans.js: a classic script (works when index.html is opened from disk, unlike fetch)
// that sets HUSS.demoData = { project, scans: [{ name, data (base64 JPEG) }] }. The main menu
// loads it only when the example is chosen.
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..', '..');
const SRC = path.join(ROOT, 'samples', 'real'), OUT = path.join(ROOT, 'demo');
const MAX_PX = 1754;   // A4 long side at 150 dpi
const QUALITY = 70;

// [file in samples/real, what it shows]
const SCANS = [
  ['trial3_01_Q4J87.jpeg', 'drawn as asked'],
  ['trial3_02_QQZZX.jpeg', 'scanned upside down: the tool turns the page'],
  ['trial3_03_92PUH.jpeg', 'ceiling rising about 3 cm: its average is measured; flagged'],
  ['trial3_04_HV93Z.jpeg', 'wall leaning strongly: its average is measured; flagged'],
  ['trial3_05_GGNEV.jpeg', 'wavy ceiling and wall'],
  ['trial3_08_93ZUF.jpeg', 'figure floating above the floor line: flagged'],
  ['trial3_10_AZPYZ.jpeg', 'figure 2 cm beside the start mark: flagged'],
  ['trial3_11_XA569.jpeg', 'ceiling drawn only right of the figure'],
  ['trial3_12_ZHQMJ.jpeg', 'QR code scribbled over: the code is read from the printed characters (tick K)'],
  ['trial3_13_A4P6Y.jpeg', 'a corner torn off: aligned from the other three corners']
];

const project = {
  format: 'huss-project', format_version: 2, project_code: 'HUSS-EXAMPLE',
  title: 'Example scans: one remembered room (ceiling 4 m, opposite wall 7 m)',
  template: 'A4L', sheet_label: 'figure', ref_height_m: 1.7, min_figure_mm: 10, foot_tolerance_mm: 4, snap_radius_mm: 1.5,
  suggestions: { figure: true, ceiling: true, wall: true },
  exclusion_criteria: [
    { id: 'excl_no_figure', label: 'Figure not drawn' },
    { id: 'excl_not_standing_full', label: 'Figure not standing or not full height' },
    { id: 'excl_not_along_axis', label: 'Section not drawn along the viewing axis' }
  ],
  structures: [{ code: 'ROOM', name: 'Remembered room', true_vertical_m: 4, true_horizontal_m: 7 }],
  rules_version: '1.3', created_at: '2026-10-05T12:00:00+03:00'
};

fs.mkdirSync(OUT, { recursive: true });
const tmp = path.join(os.tmpdir(), 'huss-demo.jpeg');
const scans = SCANS.map(([file, note], i) => {
  execFileSync('sips', ['-Z', String(MAX_PX), '-s', 'formatOptions', String(QUALITY), path.join(SRC, file), '--out', tmp], { stdio: 'ignore' });
  const data = fs.readFileSync(tmp).toString('base64');
  return { name: 'example-' + String(i + 1).padStart(2, '0') + '.jpeg', from: file, note, data };
});
const js = '/* HuSS Scorer — demo/demo-scans.js: example scans for "Try with example scans".\n' +
  ' * Generated by tests/tools/make-demo.js from samples/real (the author\'s trial 3, shared with his\n' +
  ' * consent); do not edit. Loaded only when the example is chosen on the main menu. */\n' +
  '(function (root) {\n  \'use strict\';\n  var HUSS = root.HUSS = root.HUSS || {};\n  HUSS.demoData = ' +
  JSON.stringify({ project, scans: scans.map(({ name, from, note, data }) => ({ name, from, note, data })) }) +
  ';\n})(typeof globalThis !== \'undefined\' ? globalThis : this);\n';
fs.writeFileSync(path.join(OUT, 'demo-scans.js'), js);
const readme = '# Example scans\n\n`demo-scans.js` holds ten scans of the author\'s trial 3 (from `samples/real`, scaled to 150 dpi) and an example project with one structure: a remembered room, ceiling 4 m, opposite wall 7 m. Main menu → **Try with example scans** loads them and starts an Open mode session (rater code DEMO); nothing is uploaded.\n\nMade with `node tests/tools/make-demo.js`.\n\n| File | From | Shows |\n|---|---|---|\n' +
  scans.map((s) => '| ' + s.name + ' | ' + s.from + ' | ' + s.note + ' |').join('\n') + '\n';
fs.writeFileSync(path.join(OUT, 'README.md'), readme);
console.log('demo/demo-scans.js', Math.round(js.length / 1024) + ' KB', scans.length + ' scans');
